import type { SpeciesFeatures } from './schema';

/**
 * BUILD-TIME ASSET — per-species identification features.
 *
 * Generated by an LLM (Claude) against the controlled vocabularies in
 * schema.ts, from knowledge of British butterflies. This is precomputed
 * reasoning: at runtime the app only scores against these records, never an LLM.
 *
 * ⚠️ VERIFY before relying on it in the field — flight periods especially
 * should be traced to authoritative phenology (Butterfly Conservation /
 * UK Butterflies / GBIF records) rather than model recall. Colours, habitats
 * and markings are the salient identification cues, not exhaustive.
 *
 * Keyed by scientific name to join the reference table (db/butterflies.ts).
 */
export const SPECIES_FEATURES: SpeciesFeatures[] = [
  { scientificName: 'Vanessa atalanta', flightMonths: [5, 6, 7, 8, 9, 10], colours: ['black', 'red', 'white', 'orange'], sizeClass: 'medium', wingspanMm: [64, 78], habitats: ['garden', 'hedgerow', 'woodland_edge', 'wasteland'], markings: ['white_spots', 'dark_border'] },
  { scientificName: 'Vanessa cardui', flightMonths: [5, 6, 7, 8, 9, 10], colours: ['orange', 'brown', 'black', 'white'], sizeClass: 'medium', wingspanMm: [58, 74], habitats: ['garden', 'grassland', 'wasteland', 'coastal'], markings: ['white_spots', 'spots', 'dark_border'] },
  { scientificName: 'Aglais urticae', flightMonths: [3, 4, 5, 6, 7, 8, 9, 10], colours: ['orange', 'black', 'brown', 'blue'], sizeClass: 'medium', wingspanMm: [45, 62], habitats: ['garden', 'grassland', 'wasteland', 'hedgerow'], markings: ['dark_border', 'spots', 'orange_border'] },
  { scientificName: 'Aglais io', flightMonths: [3, 4, 5, 6, 7, 8, 9], colours: ['red', 'brown', 'blue', 'black'], sizeClass: 'medium', wingspanMm: [63, 75], habitats: ['garden', 'woodland_edge', 'grassland', 'hedgerow'], markings: ['eyespots'] },
  { scientificName: 'Polygonia c-album', flightMonths: [3, 4, 5, 6, 7, 8, 9, 10], colours: ['orange', 'brown'], sizeClass: 'medium', wingspanMm: [50, 64], habitats: ['garden', 'woodland_edge', 'hedgerow'], markings: ['ragged_edge', 'comma_mark'] },
  { scientificName: 'Gonepteryx rhamni', flightMonths: [3, 4, 5, 6, 7, 8, 9], colours: ['yellow', 'green'], sizeClass: 'medium', wingspanMm: [60, 74], habitats: ['woodland', 'hedgerow', 'garden', 'scrub'], markings: ['plain'] },
  { scientificName: 'Pieris brassicae', flightMonths: [4, 5, 6, 7, 8, 9, 10], colours: ['white', 'black'], sizeClass: 'large', wingspanMm: [58, 70], habitats: ['garden', 'farmland', 'wasteland'], markings: ['dark_border', 'spots'] },
  { scientificName: 'Pieris rapae', flightMonths: [4, 5, 6, 7, 8, 9, 10], colours: ['white', 'black'], sizeClass: 'medium', wingspanMm: [38, 57], habitats: ['garden', 'farmland', 'wasteland'], markings: ['spots', 'dark_border'] },
  { scientificName: 'Pieris napi', flightMonths: [4, 5, 6, 7, 8, 9], colours: ['white', 'green', 'grey'], sizeClass: 'medium', wingspanMm: [40, 52], habitats: ['meadow', 'hedgerow', 'marsh', 'woodland_edge'], markings: ['veined', 'spots'] },
  { scientificName: 'Anthocharis cardamines', flightMonths: [4, 5, 6, 7], colours: ['white', 'orange', 'green'], sizeClass: 'medium', wingspanMm: [40, 52], habitats: ['meadow', 'hedgerow', 'woodland_edge', 'garden'], markings: ['marbled', 'spots'] },
  { scientificName: 'Celastrina argiolus', flightMonths: [4, 5, 6, 7, 8, 9], colours: ['blue', 'white', 'black'], sizeClass: 'small', wingspanMm: [26, 34], habitats: ['garden', 'hedgerow', 'woodland_edge'], markings: ['spots'] },
  { scientificName: 'Polyommatus icarus', flightMonths: [5, 6, 7, 8, 9], colours: ['blue', 'brown', 'orange'], sizeClass: 'small', wingspanMm: [29, 36], habitats: ['grassland', 'meadow', 'chalk_downland', 'coastal', 'wasteland'], markings: ['spots', 'dark_border', 'orange_border'] },
  { scientificName: 'Lycaena phlaeas', flightMonths: [4, 5, 6, 7, 8, 9, 10], colours: ['copper', 'orange', 'brown', 'black'], sizeClass: 'small', wingspanMm: [26, 36], habitats: ['grassland', 'heathland', 'wasteland', 'chalk_downland'], markings: ['spots', 'dark_border'] },
  { scientificName: 'Pararge aegeria', flightMonths: [3, 4, 5, 6, 7, 8, 9, 10], colours: ['brown', 'cream'], sizeClass: 'medium', wingspanMm: [46, 56], habitats: ['woodland', 'woodland_edge', 'hedgerow', 'garden'], markings: ['eyespots', 'spots'] },
  { scientificName: 'Pyronia tithonus', flightMonths: [7, 8], colours: ['orange', 'brown', 'black'], sizeClass: 'medium', wingspanMm: [40, 47], habitats: ['hedgerow', 'grassland', 'scrub', 'woodland_edge'], markings: ['eyespots'] },
  { scientificName: 'Maniola jurtina', flightMonths: [6, 7, 8, 9], colours: ['brown', 'orange', 'black'], sizeClass: 'medium', wingspanMm: [40, 60], habitats: ['grassland', 'meadow', 'hedgerow'], markings: ['eyespots'] },
  { scientificName: 'Aphantopus hyperantus', flightMonths: [6, 7, 8], colours: ['brown', 'black'], sizeClass: 'medium', wingspanMm: [42, 52], habitats: ['grassland', 'woodland_edge', 'hedgerow', 'meadow'], markings: ['eyespots'] },
  { scientificName: 'Coenonympha pamphilus', flightMonths: [5, 6, 7, 8, 9], colours: ['orange', 'brown'], sizeClass: 'small', wingspanMm: [33, 37], habitats: ['grassland', 'heathland', 'chalk_downland', 'moorland'], markings: ['eyespots'] },
  { scientificName: 'Ochlodes sylvanus', flightMonths: [6, 7, 8], colours: ['orange', 'brown'], sizeClass: 'small', wingspanMm: [29, 36], habitats: ['grassland', 'woodland_edge', 'hedgerow'], markings: ['spots', 'plain'] },
  { scientificName: 'Thymelicus sylvestris', flightMonths: [6, 7, 8], colours: ['orange', 'brown'], sizeClass: 'small', wingspanMm: [27, 34], habitats: ['grassland', 'meadow', 'wasteland'], markings: ['plain'] },
  { scientificName: 'Melanargia galathea', flightMonths: [6, 7, 8], colours: ['white', 'black'], sizeClass: 'medium', wingspanMm: [53, 58], habitats: ['grassland', 'chalk_downland', 'meadow'], markings: ['marbled', 'chequered', 'spots'] },
  { scientificName: 'Colias croceus', flightMonths: [5, 6, 7, 8, 9, 10], colours: ['yellow', 'orange', 'black'], sizeClass: 'medium', wingspanMm: [52, 62], habitats: ['grassland', 'chalk_downland', 'farmland', 'coastal'], markings: ['dark_border', 'spots'] },
  { scientificName: 'Thymelicus lineola', flightMonths: [7, 8], colours: ['orange', 'brown'], sizeClass: 'small', wingspanMm: [26, 30], habitats: ['grassland', 'wasteland', 'coastal'], markings: ['plain'] },
  { scientificName: 'Thymelicus acteon', flightMonths: [6, 7, 8], colours: ['brown', 'orange'], sizeClass: 'small', wingspanMm: [24, 28], habitats: ['coastal', 'chalk_downland', 'cliff'], markings: ['spots', 'plain'] },
  { scientificName: 'Hesperia comma', flightMonths: [7, 8, 9], colours: ['orange', 'brown', 'green'], sizeClass: 'small', wingspanMm: [29, 34], habitats: ['chalk_downland', 'grassland'], markings: ['white_spots', 'spots'] },
  { scientificName: 'Erynnis tages', flightMonths: [5, 6], colours: ['brown', 'grey'], sizeClass: 'small', wingspanMm: [27, 34], habitats: ['chalk_downland', 'grassland', 'heathland', 'wasteland'], markings: ['spots', 'streaked', 'plain'] },
  { scientificName: 'Pyrgus malvae', flightMonths: [4, 5, 6], colours: ['black', 'white', 'brown'], sizeClass: 'small', wingspanMm: [21, 27], habitats: ['chalk_downland', 'grassland', 'woodland_edge'], markings: ['chequered', 'white_spots'] },
  { scientificName: 'Carterocephalus palaemon', flightMonths: [5, 6], colours: ['brown', 'orange', 'gold'], sizeClass: 'small', wingspanMm: [26, 32], habitats: ['woodland_edge', 'grassland'], markings: ['chequered', 'spots'] },
  { scientificName: 'Papilio machaon', flightMonths: [5, 6, 7, 8], colours: ['yellow', 'black', 'blue', 'red'], sizeClass: 'large', wingspanMm: [76, 93], habitats: ['fen', 'marsh'], markings: ['tails', 'spots', 'dark_border', 'eyespots'] },
  { scientificName: 'Leptidea sinapis', flightMonths: [5, 6, 7], colours: ['white', 'grey'], sizeClass: 'small', wingspanMm: [36, 48], habitats: ['woodland', 'woodland_edge', 'scrub'], markings: ['plain', 'spots'] },
  { scientificName: 'Leptidea juvernica', flightMonths: [5, 6, 7, 8], colours: ['white', 'grey'], sizeClass: 'small', wingspanMm: [36, 48], habitats: ['grassland', 'hedgerow', 'scrub'], markings: ['plain', 'spots'] },
  { scientificName: 'Colias hyale', flightMonths: [7, 8, 9], colours: ['yellow', 'cream', 'black'], sizeClass: 'medium', wingspanMm: [46, 56], habitats: ['grassland', 'farmland', 'coastal'], markings: ['dark_border', 'spots'] },
  { scientificName: 'Callophrys rubi', flightMonths: [4, 5, 6], colours: ['green', 'brown'], sizeClass: 'small', wingspanMm: [27, 34], habitats: ['heathland', 'moorland', 'chalk_downland', 'scrub', 'woodland_edge'], markings: ['plain', 'white_spots'] },
  { scientificName: 'Thecla betulae', flightMonths: [7, 8, 9], colours: ['brown', 'orange', 'gold'], sizeClass: 'small', wingspanMm: [36, 45], habitats: ['hedgerow', 'woodland_edge', 'scrub'], markings: ['tails', 'orange_border', 'streaked'] },
  { scientificName: 'Favonius quercus', flightMonths: [7, 8], colours: ['purple', 'grey', 'black'], sizeClass: 'small', wingspanMm: [36, 39], habitats: ['woodland', 'woodland_edge'], markings: ['iridescent', 'streaked'] },
  { scientificName: 'Satyrium w-album', flightMonths: [6, 7, 8], colours: ['brown', 'white'], sizeClass: 'small', wingspanMm: [32, 36], habitats: ['woodland_edge', 'hedgerow'], markings: ['tails', 'streaked'] },
  { scientificName: 'Satyrium pruni', flightMonths: [6, 7], colours: ['brown', 'orange', 'black'], sizeClass: 'small', wingspanMm: [36, 39], habitats: ['woodland_edge', 'scrub', 'hedgerow'], markings: ['tails', 'orange_border', 'spots'] },
  { scientificName: 'Cupido minimus', flightMonths: [5, 6, 7, 8], colours: ['blue', 'brown', 'grey', 'black'], sizeClass: 'small', wingspanMm: [18, 27], habitats: ['chalk_downland', 'grassland', 'coastal'], markings: ['spots', 'plain'] },
  { scientificName: 'Plebejus argus', flightMonths: [6, 7, 8], colours: ['blue', 'brown', 'orange', 'black'], sizeClass: 'small', wingspanMm: [26, 32], habitats: ['heathland', 'chalk_downland', 'coastal'], markings: ['dark_border', 'spots', 'orange_border'] },
  { scientificName: 'Aricia agestis', flightMonths: [5, 6, 7, 8, 9], colours: ['brown', 'orange', 'black'], sizeClass: 'small', wingspanMm: [25, 31], habitats: ['chalk_downland', 'grassland', 'coastal', 'wasteland'], markings: ['orange_border', 'spots', 'dark_border'] },
  { scientificName: 'Aricia artaxerxes', flightMonths: [6, 7], colours: ['brown', 'orange', 'white'], sizeClass: 'small', wingspanMm: [25, 31], habitats: ['grassland', 'chalk_downland', 'moorland'], markings: ['white_spots', 'orange_border', 'spots'] },
  { scientificName: 'Polyommatus coridon', flightMonths: [7, 8, 9], colours: ['blue', 'brown', 'black'], sizeClass: 'small', wingspanMm: [30, 36], habitats: ['chalk_downland', 'grassland'], markings: ['dark_border', 'chequered', 'spots'] },
  { scientificName: 'Polyommatus bellargus', flightMonths: [5, 6, 8, 9], colours: ['blue', 'black', 'white'], sizeClass: 'small', wingspanMm: [30, 36], habitats: ['chalk_downland', 'grassland'], markings: ['dark_border', 'chequered', 'spots'] },
  { scientificName: 'Phengaris arion', flightMonths: [6, 7], colours: ['blue', 'black', 'grey'], sizeClass: 'small', wingspanMm: [38, 48], habitats: ['grassland', 'chalk_downland', 'coastal'], markings: ['spots', 'dark_border'] },
  { scientificName: 'Lampides boeticus', flightMonths: [8, 9, 10], colours: ['blue', 'brown', 'purple'], sizeClass: 'small', wingspanMm: [24, 32], habitats: ['coastal', 'garden', 'wasteland'], markings: ['tails', 'eyespots', 'spots'] },
  { scientificName: 'Hamearis lucina', flightMonths: [5, 6], colours: ['orange', 'brown', 'black'], sizeClass: 'small', wingspanMm: [29, 34], habitats: ['chalk_downland', 'woodland_edge', 'grassland', 'scrub'], markings: ['chequered', 'spots'] },
  { scientificName: 'Limenitis camilla', flightMonths: [6, 7, 8], colours: ['black', 'white', 'brown'], sizeClass: 'medium', wingspanMm: [56, 64], habitats: ['woodland', 'woodland_edge'], markings: ['white_spots', 'plain'] },
  { scientificName: 'Apatura iris', flightMonths: [6, 7, 8], colours: ['purple', 'black', 'white'], sizeClass: 'large', wingspanMm: [75, 84], habitats: ['woodland'], markings: ['iridescent', 'white_spots'] },
  { scientificName: 'Argynnis paphia', flightMonths: [6, 7, 8], colours: ['orange', 'brown', 'black', 'green'], sizeClass: 'large', wingspanMm: [69, 80], habitats: ['woodland', 'woodland_edge'], markings: ['spots', 'streaked'] },
  { scientificName: 'Fabriciana adippe', flightMonths: [6, 7, 8], colours: ['orange', 'brown', 'black'], sizeClass: 'medium', wingspanMm: [60, 67], habitats: ['woodland_edge', 'moorland', 'grassland'], markings: ['spots', 'white_spots'] },
  { scientificName: 'Speyeria aglaja', flightMonths: [6, 7, 8], colours: ['orange', 'brown', 'green', 'black'], sizeClass: 'medium', wingspanMm: [58, 68], habitats: ['grassland', 'chalk_downland', 'moorland', 'coastal'], markings: ['spots', 'white_spots'] },
  { scientificName: 'Boloria euphrosyne', flightMonths: [4, 5, 6], colours: ['orange', 'brown', 'black'], sizeClass: 'medium', wingspanMm: [44, 47], habitats: ['woodland_edge', 'grassland', 'moorland'], markings: ['spots', 'white_spots'] },
  { scientificName: 'Boloria selene', flightMonths: [5, 6, 7], colours: ['orange', 'brown', 'black'], sizeClass: 'medium', wingspanMm: [41, 44], habitats: ['woodland_edge', 'grassland', 'moorland', 'marsh'], markings: ['spots', 'white_spots'] },
  { scientificName: 'Euphydryas aurinia', flightMonths: [5, 6], colours: ['orange', 'brown', 'cream', 'black'], sizeClass: 'medium', wingspanMm: [42, 48], habitats: ['grassland', 'marsh', 'chalk_downland'], markings: ['chequered', 'spots'] },
  { scientificName: 'Melitaea cinxia', flightMonths: [5, 6], colours: ['orange', 'brown', 'black', 'cream'], sizeClass: 'medium', wingspanMm: [38, 46], habitats: ['coastal', 'cliff', 'grassland'], markings: ['chequered', 'spots'] },
  { scientificName: 'Melitaea athalia', flightMonths: [5, 6, 7], colours: ['orange', 'brown', 'cream', 'black'], sizeClass: 'medium', wingspanMm: [39, 47], habitats: ['woodland', 'heathland', 'grassland'], markings: ['chequered', 'spots'] },
  { scientificName: 'Issoria lathonia', flightMonths: [7, 8, 9], colours: ['orange', 'brown', 'black'], sizeClass: 'medium', wingspanMm: [40, 45], habitats: ['grassland', 'farmland', 'coastal'], markings: ['spots', 'white_spots'] },
  { scientificName: 'Nymphalis antiopa', flightMonths: [7, 8, 9], colours: ['purple', 'brown', 'cream', 'blue'], sizeClass: 'large', wingspanMm: [60, 70], habitats: ['woodland', 'garden', 'wasteland'], markings: ['dark_border', 'spots', 'orange_border'] },
  { scientificName: 'Danaus plexippus', flightMonths: [9, 10], colours: ['orange', 'black', 'white'], sizeClass: 'large', wingspanMm: [90, 100], habitats: ['coastal', 'garden', 'wasteland'], markings: ['veined', 'white_spots', 'dark_border'] },
  { scientificName: 'Lasiommata megera', flightMonths: [5, 6, 8, 9], colours: ['orange', 'brown', 'black'], sizeClass: 'medium', wingspanMm: [44, 52], habitats: ['coastal', 'grassland', 'wasteland', 'chalk_downland'], markings: ['eyespots', 'spots'] },
  { scientificName: 'Erebia epiphron', flightMonths: [6, 7], colours: ['brown', 'orange', 'black'], sizeClass: 'small', wingspanMm: [35, 40], habitats: ['mountain', 'moorland'], markings: ['eyespots', 'spots'] },
  { scientificName: 'Erebia aethiops', flightMonths: [7, 8], colours: ['brown', 'orange', 'black', 'white'], sizeClass: 'medium', wingspanMm: [46, 52], habitats: ['moorland', 'grassland', 'woodland_edge'], markings: ['eyespots', 'orange_border'] },
  { scientificName: 'Hipparchia semele', flightMonths: [7, 8, 9], colours: ['grey', 'brown', 'orange', 'black'], sizeClass: 'medium', wingspanMm: [51, 62], habitats: ['heathland', 'coastal', 'cliff', 'grassland'], markings: ['eyespots', 'marbled'] },
  { scientificName: 'Coenonympha tullia', flightMonths: [6, 7, 8], colours: ['orange', 'brown', 'grey'], sizeClass: 'small', wingspanMm: [35, 40], habitats: ['bog', 'moorland'], markings: ['eyespots', 'spots'] },
];
